version: "3"
services:
  anime-scraper:
    build: .
    image: anime-scraper:latest
    container_name: anime-scraper
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      LANGUAGE: ${LANGUAGE}
    links:
      - chrome  
  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

